import { useRef, useState, type FormEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import Workspace, { Heading, Panel, Notice, Review, Badge, Empty, LoadState, ErrorMessage } from '../../components/Workspace/Workspace';
import { Field } from '../../components/Workspace/Forms';
import { companyPaymentLabel, jobTone } from '../../utils/companyProject';
import { useCompanyJobs, type CompanyTransition } from '../../context/CompanyJobsContext';
import { useWorkforce } from '../../context/WorkforceContext';
import type { CompanyJob } from '../../types/job';
import { getJobStatusLabel } from '../../utils/jobLabels';
import { getWorkerStatusLabel } from '../../utils/workerLables';
import { formatCurrency } from '../../utils/quoteMath';
import { dateInputToUtc } from '../../utils/dates';
import { projectDate } from '../../utils/customerProject';

function JobContent({ job }: { job: CompanyJob }) {
  const { transitionJob, updateJobQuote, updateJobEndDate, refreshJobs } = useCompanyJobs();
  const workforce = useWorkforce();
  const [quote, setQuote] = useState(job.quoteAmount > 0 ? String(job.quoteAmount) : ''), [endDate, setEndDate] = useState(job.endDate?.slice(0, 10) ?? ''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const saving = useRef(false);
  const quoted = !!job.quoteSentAt, consent = !!job.quoteAcceptedAt;
  const canQuote = job.status === 'accepted' && !consent && !job.paymentRequested;
  const assigned = workforce.workers.filter(w => w.jobId === job.id);
  const next = job.status === 'requested' ? ['Review this request', 'Accept or reject before you quote or assign workers.'] : canQuote ? quoted ? ['Await customer acceptance', 'Your quote is with the customer. Work cannot start until they accept it.'] : ['Send a quote', 'The request is accepted. Set the amount for the customer to review.'] : job.status === 'accepted' && consent ? ['Ready to start work', 'The customer has accepted the quote. You can start the project.'] : job.status === 'in-progress' ? ['Keep the work moving', 'Complete the job when the agreed work is finished.'] : ['Project closed', 'The job is closed. Payment status is tracked separately.'];
  const perform = async (action: () => Promise<void>, confirmation?: string) => { if (saving.current || (confirmation && !window.confirm(confirmation))) return; saving.current = true; setBusy(true); setError(''); try { await action(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save this change.'); } finally { saving.current = false; setBusy(false); } };
  const transition = (action: CompanyTransition, message: string) => void perform(() => transitionJob(job.id, action), message);
  const send = (event: FormEvent) => { event.preventDefault(); void perform(() => updateJobQuote(job.id, Number(quote)), 'Send this quote for the customer to review?'); };
  return <><Heading title={job.title} description={`Project ${job.id.slice(-6).toUpperCase()} · ${job.dateRange}`} eyebrow="PROJECT MANAGEMENT" action={<Link className="secondary" to="/company/jobs">← All projects</Link>} /><div className="status-line"><Badge tone={jobTone(job)}>{getJobStatusLabel(job.status)}</Badge><span className="meta">Payment: {companyPaymentLabel(job)}</span></div><Notice title={next[0]}>{next[1]}</Notice><ErrorMessage error={error} retry={refreshJobs} />
    <div className="split"><div className="stack"><section className="requestdetail"><span className="eyebrow">THE PROJECT BRIEF</span><h2>Project scope</h2><p className="scope">{job.description}</p><dl className="schedule"><div><dt>Proposed start</dt><dd>{projectDate(job.startDate)}</dd></div><div><dt>Proposed end</dt><dd>{projectDate(job.endDate)}</dd></div><div><dt>Working days</dt><dd>{job.daysWorking ?? 'Unavailable'}</dd></div></dl><div className="divider" /><span className="eyebrow">PROJECT LOCATION</span><p className="subtext">{job.address ? [job.address.streetAddress, job.address.suburb, job.address.city, job.address.province, String(job.address.postalCode).padStart(4, '0')].join(', ') : 'Location unavailable'}</p>
      {job.status === 'accepted' && <form className="formsection" onSubmit={event => { event.preventDefault(); void perform(() => updateJobEndDate(job.id, dateInputToUtc(endDate))); }}><Field label="Update planned end date"><input type="date" value={endDate} onChange={e => setEndDate(e.target.value)} min={job.startDate?.slice(0, 10)} required disabled={busy} /></Field><button className="secondary" style={{ marginTop: 12 }} disabled={busy}>Save end date</button></form>}
    </section><Panel title="Quote & payment"><Badge tone={consent ? 'green' : ''}>{consent ? 'Accepted by customer' : quoted ? 'Awaiting acceptance' : 'Not sent'}</Badge><div className="divider" />{quoted && <div className="money">{formatCurrency(job.quoteAmount)}</div>}{canQuote && <form onSubmit={send}><Field label="Quote amount · ZAR"><input type="number" name="quote" value={quote} onChange={e => setQuote(e.target.value)} min="0.01" step="0.01" max="99999999.99" required disabled={busy} /></Field><button className="primary" style={{ marginTop: 12 }} disabled={busy}>{busy ? 'Saving…' : quoted ? 'Send revised quote →' : 'Send quote →'}</button></form>}{!quoted && !canQuote && <p>No company quote has been sent.</p>}<p className="hint">{consent ? `Customer accepted on ${projectDate(job.quoteAcceptedAt)}. The amount is locked.` : quoted ? `Sent ${projectDate(job.quoteSentAt)}. Only the customer can accept this amount.` : 'The company must accept the job first.'}</p><div className="divider" /><Review items={[["Simulated payment", companyPaymentLabel(job)], ["Amount marked paid", formatCurrency(job.amountPaid)], ["Demo reference", job.paymentRequested ? job.paymentNote : 'Not submitted']]} /><p className="hint">Job progress does not mark a payment successful. The customer submits a simulated EFT after accepting the quote; an administrator reviews it.</p></Panel>
    <Panel title="Assigned workers"><Link className="textbutton" to={'/company/workforce?jobId=' + job.id}>Manage workforce →</Link><LoadState loading={workforce.loading} error={workforce.error} retry={workforce.refreshWorkers} />{!workforce.loading && !workforce.error && (assigned.length ? assigned.map(w => <div className="workerrow" key={w.workerId}><div><strong>{w.workerFirstName} {w.workerLastName}</strong><small style={{ display: 'block' }}>{getWorkerStatusLabel(w.workerStatus)} · Assigned</small></div><button className="secondary" disabled={busy} onClick={() => void perform(() => workforce.assignWorker(w.workerId, null), 'Unassign this worker while keeping the workforce record?')}>Unassign</button></div>) : <p>{job.status === 'requested' ? 'Accept this request before assigning workers.' : 'No workers are assigned to this project.'}</p>)}</Panel></div>
    <aside className="stack"><Panel title={next[0]}><p>{next[1]}</p><div className="buttonrow" style={{ marginTop: 20 }}>{job.status === 'requested' && <><button className="primary" disabled={busy} onClick={() => transition('accept', 'Accept this project request?')}>Accept request</button><button className="danger" disabled={busy} onClick={() => transition('reject', 'Reject this project request?')}>Reject</button></>}{job.status === 'accepted' && consent && <button className="primary wide" disabled={busy} onClick={() => transition('start', 'Start work on this project?')}>Start work →</button>}{job.status === 'in-progress' && <button className="primary wide" disabled={busy} onClick={() => transition('complete', 'Complete this project? Its workers will be unassigned.')}>Complete project →</button>}</div></Panel><Panel title="Project milestones"><ol className="timeline"><li>Request received</li><li className={job.acceptedAt ? 'current' : ''}>Company accepted<small>{job.acceptedAt ? projectDate(job.acceptedAt) : 'Awaiting decision'}</small></li><li className={quoted ? 'current' : ''}>Quote sent<small>{quoted ? projectDate(job.quoteSentAt) : 'Not sent'}</small></li><li className={consent ? 'current' : ''}>Customer accepted quote<small>{consent ? projectDate(job.quoteAcceptedAt) : 'Awaiting agreement'}</small></li><li className="current">Current job status<small>{getJobStatusLabel(job.status)}</small></li></ol></Panel></aside></div>
  </>;
}
export default function CompanyJobManagement() {
  const { jobId } = useParams();
  const { jobs, loading, error, refreshJobs } = useCompanyJobs();
  const job = jobs.find(j => j.id === jobId);
  return <Workspace title="Company job management"><LoadState loading={loading} error={error} retry={refreshJobs} />{!loading && !error && (job ? <JobContent key={`${job.id}:${job.status}:${job.quoteAmount}:${job.quoteSentAt}:${job.quoteAcceptedAt}:${job.endDate}`} job={job} /> : <Empty><h1>Project not found</h1><p>This project is unavailable for your company.</p><Link className="secondary" to="/company/jobs">Back to projects</Link></Empty>)}</Workspace>;
}
