// <auto-generated />
using System;
using BuildAndHire.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildAndHire.Infrastructure.Migrations
{
    [DbContext(typeof(BuildAndHireDbContext))]
    [Migration("20260812101311_AdminAccounts")]
    partial class AdminAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildAndHire.Domain.Models.Admin", b =>
                {
                    b.Property<Guid>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdminRole")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("BuildAndHire.Domain.Models.Companies", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.HasIndex("CompanyEmail")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = new Guid("a1111111-0000-0000-0000-000000000001"),
                            CompanyEmail = "info@capecoastalconstruction.co.za",
                            CompanyName = "Cape Coastal Construction (Pty) Ltd",
                            Password = "Password123!",
                            RegistrationNumber = "2015/123456/07",
                            Status = 0,
                            TaxNumber = "9012345671"
                        },
                        new
                        {
                            CompanyId = new Guid("a1111111-0000-0000-0000-000000000002"),
                            CompanyEmail = "admin@joburgrise.co.za",
                            CompanyName = "Joburg Rise Builders",
                            Password = "Password123!",
                            RegistrationNumber = "2017/654321/07",
                            Status = 0,
                            TaxNumber = "9012345672"
                        },
                        new
                        {
                            CompanyId = new Guid("a1111111-0000-0000-0000-000000000003"),
                            CompanyEmail = "contracts@durbanbay.co.za",
                            CompanyName = "Durban Bay Contractors",
                            Password = "Password123!",
                            RegistrationNumber = "2019/789012/07",
                            Status = 1,
                            TaxNumber = "9012345673"
                        });
                });

            modelBuilder.Entity("BuildAndHire.Domain.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("b2222222-0000-0000-0000-000000000001"),
                            CustomerName = "Thandiwe Mahlangu",
                            Email = "thandiwe.mahlangu@example.com",
                            Password = "Password123!",
                            Status = 0
                        },
                        new
                        {
                            CustomerId = new Guid("b2222222-0000-0000-0000-000000000002"),
                            CustomerName = "Johan van der Berg",
                            Email = "johan.vdberg@example.com",
                            Password = "Password123!",
                            Status = 0
                        },
                        new
                        {
                            CustomerId = new Guid("b2222222-0000-0000-0000-000000000003"),
                            CustomerName = "Aisha Patel",
                            Email = "aisha.patel@example.com",
                            Password = "Password123!",
                            Status = 0
                        },
                        new
                        {
                            CustomerId = new Guid("b2222222-0000-0000-0000-000000000004"),
                            CustomerName = "Sipho Ndlovu",
                            Email = "sipho.ndlovu@example.com",
                            Password = "Password123!",
                            Status = 0
                        });
                });

            modelBuilder.Entity("BuildAndHire.Domain.Models.Jobs", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DailyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("DaysWorking")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PayingMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("BuildAndHire.Domain.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("BuildAndHire.Domain.Models.Workers", b =>
                {
                    b.Property<Guid>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WorkerFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerLastNAme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkerStatus")
                        .HasColumnType("int");

                    b.HasKey("WorkerId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("BuildAndHire.Domain.Models.Companies", b =>
                {
                    b.OwnsOne("BuildAndHire.Domain.ValueObjects.Address", "address", b1 =>
                        {
                            b1.Property<Guid>("CompaniesCompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AddressId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("PostalCode")
                                .HasColumnType("int");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Suburb")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CompaniesCompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompaniesCompanyId");

                            b1.HasData(
                                new
                                {
                                    CompaniesCompanyId = new Guid("a1111111-0000-0000-0000-000000000001"),
                                    AddressId = new Guid("f1111111-0000-0000-0000-000000000001"),
                                    City = "Cape Town",
                                    PostalCode = 8001,
                                    Province = "Western Cape",
                                    StreetAddress = "12 Long Street",
                                    Suburb = "Cape Town City Centre"
                                },
                                new
                                {
                                    CompaniesCompanyId = new Guid("a1111111-0000-0000-0000-000000000002"),
                                    AddressId = new Guid("f1111111-0000-0000-0000-000000000002"),
                                    City = "Johannesburg",
                                    PostalCode = 2196,
                                    Province = "Gauteng",
                                    StreetAddress = "45 Jan Smuts Avenue",
                                    Suburb = "Rosebank"
                                },
                                new
                                {
                                    CompaniesCompanyId = new Guid("a1111111-0000-0000-0000-000000000003"),
                                    AddressId = new Guid("f1111111-0000-0000-0000-000000000003"),
                                    City = "Durban",
                                    PostalCode = 4001,
                                    Province = "KwaZulu-Natal",
                                    StreetAddress = "78 Marine Parade",
                                    Suburb = "Durban Central"
                                });
                        });

                    b.Navigation("address")
                        .IsRequired();
                });

            modelBuilder.Entity("BuildAndHire.Domain.Models.Customer", b =>
                {
                    b.OwnsOne("BuildAndHire.Domain.ValueObjects.Address", "address", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AddressId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("PostalCode")
                                .HasColumnType("int");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Suburb")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("b2222222-0000-0000-0000-000000000001"),
                                    AddressId = new Guid("f2222222-0000-0000-0000-000000000001"),
                                    City = "Cape Town",
                                    PostalCode = 8001,
                                    Province = "Western Cape",
                                    StreetAddress = "23 Kloof Street",
                                    Suburb = "Gardens"
                                },
                                new
                                {
                                    CustomerId = new Guid("b2222222-0000-0000-0000-000000000002"),
                                    AddressId = new Guid("f2222222-0000-0000-0000-000000000002"),
                                    City = "Cape Town",
                                    PostalCode = 7530,
                                    Province = "Western Cape",
                                    StreetAddress = "9 Voortrekker Road",
                                    Suburb = "Bellville"
                                },
                                new
                                {
                                    CustomerId = new Guid("b2222222-0000-0000-0000-000000000003"),
                                    AddressId = new Guid("f2222222-0000-0000-0000-000000000003"),
                                    City = "Johannesburg",
                                    PostalCode = 2196,
                                    Province = "Gauteng",
                                    StreetAddress = "156 Oxford Road",
                                    Suburb = "Melrose"
                                },
                                new
                                {
                                    CustomerId = new Guid("b2222222-0000-0000-0000-000000000004"),
                                    AddressId = new Guid("f2222222-0000-0000-0000-000000000004"),
                                    City = "Durban",
                                    PostalCode = 4001,
                                    Province = "KwaZulu-Natal",
                                    StreetAddress = "34 Point Road",
                                    Suburb = "Point"
                                });
                        });

                    b.Navigation("address")
                        .IsRequired();
                });

            modelBuilder.Entity("BuildAndHire.Domain.Models.Jobs", b =>
                {
                    b.HasOne("BuildAndHire.Domain.Models.Companies", "companies")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BuildAndHire.Domain.Models.Customer", "customer")
                        .WithMany("Jobs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("BuildAndHire.Domain.ValueObjects.Address", "address", b1 =>
                        {
                            b1.Property<Guid>("JobsJobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AddressId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("PostalCode")
                                .HasColumnType("int");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Suburb")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("JobsJobId");

                            b1.ToTable("Jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobsJobId");
                        });

                    b.Navigation("address")
                        .IsRequired();

                    b.Navigation("companies");

                    b.Navigation("customer");
                });

            modelBuilder.Entity("BuildAndHire.Domain.Models.Payment", b =>
                {
                    b.HasOne("BuildAndHire.Domain.Models.Customer", null)
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId");

                    b.HasOne("BuildAndHire.Domain.Models.Jobs", "Job")
                        .WithOne("Payment")
                        .HasForeignKey("BuildAndHire.Domain.Models.Payment", "JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("BuildAndHire.Domain.Models.Workers", b =>
                {
                    b.HasOne("BuildAndHire.Domain.Models.Companies", "ResidingCompany")
                        .WithMany("Workers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BuildAndHire.Domain.Models.Jobs", "Job")
                        .WithMany("Workers")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("ResidingCompany");
                });

            modelBuilder.Entity("BuildAndHire.Domain.Models.Companies", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("BuildAndHire.Domain.Models.Customer", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BuildAndHire.Domain.Models.Jobs", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Workers");
                });
#pragma warning restore 612, 618
        }
    }
}
