import { useRef, useState } from 'react';
import Workspace, { Heading, Stats, Notice, Badge, LoadState, ErrorMessage, Empty, Review } from '../../components/Workspace/Workspace';
import Modal from '../../components/Workspace/Modal';
import { useApiResource, dataChanged } from '../../hooks/useApiResource';
import { apiRequest, ApiError } from '../../utils/api';
import { AccountStatus, PaymentEnum } from '../../types/enums';
import { formatCurrency } from '../../utils/quoteMath';
import { projectDate } from '../../utils/customerProject';
interface Company { companyId: string; companyName: string; status: AccountStatus; address?: { city: string } | null; }
interface Customer { customerId: string; customerName: string; status: AccountStatus; address?: { city: string } | null; }
interface Payment { paymentId: string; jobId: string; amount: number; status: PaymentEnum; paymentDate: string; transactionReference: string | null; }
interface Job { jobId: string; jobDescription: string; }
const statusName = (status: AccountStatus) => status === AccountStatus.Active ? 'Active' : status === AccountStatus.InActive ? 'Inactive' : status === AccountStatus.Pending ? 'Pending' : status === AccountStatus.Deleted ? 'Deleted' : status === AccountStatus.Available ? 'Available' : 'Unavailable';
const paymentName = (status: PaymentEnum) => status === PaymentEnum.Pending ? 'Pending review' : status === PaymentEnum.Successful ? 'Successful' : status === PaymentEnum.Failed ? 'Failed' : 'Refunded';
export default function AdminPortal() {
  const companies = useApiResource<Company[]>('/api/Companies'), customers = useApiResource<Customer[]>('/api/Customer'), payments = useApiResource<Payment[]>('/api/Payment'), jobs = useApiResource<Job[]>('/api/Jobs');
  const [tab, setTab] = useState<'companies' | 'customers' | 'payments'>('companies'), [search, setSearch] = useState(''), [selected, setSelected] = useState<Payment | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const saving = useRef(false);
  const refresh = () => { companies.refresh(); customers.refresh(); payments.refresh(); jobs.refresh(); };
  const perform = async (action: () => Promise<unknown>, question: string) => { if (saving.current || !window.confirm(question)) return; saving.current = true; setBusy(true); setError(''); try { await action(); setSelected(null); dataChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save this decision.'); if (reason instanceof ApiError && reason.status === 409) { setSelected(null); refresh(); } } finally { saving.current = false; setBusy(false); } };
  const update = (id: string, status: AccountStatus, company: boolean, name: string) => void perform(() => apiRequest(`/api/${company ? 'Companies' : 'Customer'}/${id}/${company ? 'Status' : 'status'}`, { method: 'PATCH', body: JSON.stringify({ status }) }), `Set ${name} to ${statusName(status).toLowerCase()}?`);
  const resource = tab === 'companies' ? companies : tab === 'customers' ? customers : payments;
  const accounts = tab === 'companies' ? (companies.data ?? []).map(c => ({ id: c.companyId, name: c.companyName, status: c.status, city: c.address?.city })) : (customers.data ?? []).map(c => ({ id: c.customerId, name: c.customerName, status: c.status, city: c.address?.city }));
  const visible = accounts.filter(a => a.name.toLowerCase().includes(search.trim().toLowerCase()));
  const paymentTitle = (payment: Payment) => jobs.data?.find(j => j.jobId === payment.jobId)?.jobDescription ?? `Project ${payment.jobId.slice(-6).toUpperCase()}`;
  const visiblePayments = (payments.data ?? []).filter(p => (paymentTitle(p) + ' ' + (p.transactionReference ?? '')).toLowerCase().includes(search.trim().toLowerCase()));
  return <Workspace title="Admin portal"><Heading title="Keep the platform moving." description="Review company accounts, manage customers and record simulated payment outcomes." eyebrow="ADMIN WORKSPACE" />
  <Stats items={[["Pending companies", companies.data?.filter(c => c.status === AccountStatus.Pending).length ?? '—', "Account approval needed"], ["Active customers", customers.data?.filter(c => c.status === AccountStatus.Active).length ?? '—', "Enabled customer accounts"], ["Pending payments", payments.data?.filter(p => p.status === PaymentEnum.Pending).length ?? '—', "Simulated EFT review"]]} /><div className="toolbar"><div className="tabs" aria-label="Admin sections">{(['companies', 'customers', 'payments'] as const).map(t => <button key={t} className={`tab ${tab === t ? 'active' : ''}`} aria-pressed={tab === t} onClick={() => { setTab(t); setSearch(''); setError(''); }}>{t === 'companies' ? 'Companies' : t === 'customers' ? 'Customers' : 'Simulated payments'}</button>)}</div><input className="search" type="search" value={search} onChange={e => setSearch(e.target.value)} placeholder={tab === 'payments' ? 'Search project or reference…' : 'Search account name…'} aria-label="Search admin records" /></div><ErrorMessage error={error} retry={refresh} /><LoadState loading={resource.loading} error={resource.error} retry={resource.refresh} />
  {!resource.loading && !resource.error && (tab !== 'payments' ? <><div className="tablewrap"><div className="tabletitle"><h2>{tab === 'companies' ? 'Company account review' : 'Customer accounts'}</h2><small>Manage account access</small></div><table><thead><tr><th>{tab === 'companies' ? 'Company' : 'Customer'}</th><th>City</th><th>Account status</th><th>Decision</th></tr></thead><tbody>{visible.map(a => <tr key={a.id}><td><strong>{a.name}</strong><small>{tab === 'companies' ? 'Company' : 'Customer'} account</small></td><td data-label="City">{a.city ?? 'Unavailable'}</td><td data-label="Status"><Badge tone={a.status === AccountStatus.Active ? 'green' : a.status === AccountStatus.Pending ? '' : 'gray'}>{statusName(a.status)}</Badge></td><td data-label="Decision"><div className="pills">{tab === 'companies' && a.status === AccountStatus.Pending ? <><button className="primary" disabled={busy} onClick={() => update(a.id, AccountStatus.Active, true, a.name)}>Approve</button><button className="danger" disabled={busy} onClick={() => update(a.id, AccountStatus.InActive, true, a.name)}>Reject</button></> : <button className="secondary" disabled={busy} onClick={() => update(a.id, a.status === AccountStatus.Active ? AccountStatus.InActive : AccountStatus.Active, tab === 'companies', a.name)}>{a.status === AccountStatus.Active ? 'Deactivate' : 'Restore'}</button>}</div></td></tr>)}</tbody></table></div>{!visible.length && <Empty>No accounts match this view.</Empty>}</> : <><Notice title="Payment simulation only">These records represent demo outcomes. No funds move and no bank details are required.</Notice><ErrorMessage error={jobs.error} retry={jobs.refresh} /><div className="tablewrap"><div className="tabletitle"><h2>Simulated EFT records</h2><small>Pending → one final outcome</small></div><table><thead><tr><th>Project & reference</th><th>Amount</th><th>Payment status</th><th>Action</th></tr></thead><tbody>{visiblePayments.map(p => <tr key={p.paymentId}><td><strong>{paymentTitle(p)}</strong><small>{p.transactionReference ?? 'No demo reference'} · {projectDate(p.paymentDate)}</small></td><td data-label="Amount">{formatCurrency(p.amount)}</td><td data-label="Payment status"><Badge tone={p.status === PaymentEnum.Successful ? 'green' : p.status === PaymentEnum.Failed ? 'red' : ''}>{paymentName(p.status)}</Badge></td><td data-label="Action">{p.status === PaymentEnum.Pending ? <button className="secondary" disabled={busy} onClick={() => { setSelected(p); setError(''); }}>Review</button> : <small>Final outcome recorded</small>}</td></tr>)}</tbody></table></div>{!visiblePayments.length && <Empty>No simulated payments match this view.</Empty>}<div className="fieldnote">Amounts come from the accepted quote. A reviewed record cannot be submitted again or switched to another outcome.</div></>)}
  {selected && <Modal title="Record a demo outcome" onClose={() => { if (!busy) setSelected(null); }}><span className="eyebrow">SIMULATED PAYMENT REVIEW</span><p className="subtext">{paymentTitle(selected)}</p><div className="money" style={{ margin: '18px 0' }}>{formatCurrency(selected.amount)}</div><Review items={[["Demo reference", selected.transactionReference ?? 'None'], ["Requested", projectDate(selected.paymentDate)], ["Current status", paymentName(selected.status)]]} /><ErrorMessage error={error} /><div className="fieldnote">Choose one final outcome for this pending record. No money moves.</div><div className="buttonrow"><button className="secondary" disabled={busy} onClick={() => setSelected(null)}>Cancel</button>{[PaymentEnum.Failed, PaymentEnum.Successful].map(status => <button key={status} disabled={busy} className={status === PaymentEnum.Failed ? 'danger' : 'primary'} onClick={() => void perform(() => apiRequest(`/api/Payment/${selected.paymentId}/status`, { method: 'PATCH', body: JSON.stringify({ status }) }), `Record ${paymentName(status).toLowerCase()} as this simulated payment's final outcome?`)}>{status === PaymentEnum.Failed ? 'Mark failed' : 'Mark successful'}</button>)}</div></Modal>}
  </Workspace>;
}
