import { useRef, useState, type FormEvent } from 'react';
import Workspace, { Heading, Badge, LoadState, ErrorMessage, Empty } from '../../components/Workspace/Workspace';
import { Field } from '../../components/Workspace/Forms';
import Modal from '../../components/Workspace/Modal';
import { useAdminManagement } from '../../context/AdminManagementContext';
import { AdminRole, type Admin } from '../../types/admin';
import { AccountStatus } from '../../types/enums';
export default function AdminManagement() {
  const context = useAdminManagement();
  const [search, setSearch] = useState(''), [filter, setFilter] = useState('all'), [editing, setEditing] = useState<Admin | null | undefined>(undefined);
  const [name, setName] = useState(''), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [role, setRole] = useState<AdminRole>(AdminRole.Admin), [status, setStatus] = useState<AccountStatus>(AccountStatus.Active), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const saving = useRef(false);
  const visible = context.admins.filter(a => (filter === 'all' || String(a.status) === filter) && (a.userName + ' ' + a.email).toLowerCase().includes(search.trim().toLowerCase()));
  const open = (admin: Admin | null) => { setEditing(admin); setName(admin?.userName ?? ''); setEmail(admin?.email ?? ''); setPassword(''); setRole(admin?.adminRole ?? AdminRole.Admin); setStatus(admin?.status ?? AccountStatus.Active); setError(''); };
  const perform = async (action: () => Promise<unknown>, question: string) => { if (saving.current || !window.confirm(question)) return; saving.current = true; setBusy(true); setError(''); try { await action(); setEditing(undefined); setPassword(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save the administrator.'); } finally { saving.current = false; setBusy(false); } };
  const submit = (event: FormEvent) => { event.preventDefault(); if (!name.trim()) { setError('A name is required.'); return; } const input = { userName: name.trim(), email: email.trim(), adminRole: role, status, ...(password ? { password } : {}) }; void perform(() => editing ? context.updateAdmin(editing.adminId, input) : context.createAdmin({ ...input, password }), `Save ${name.trim()} as ${role === AdminRole.SuperAdmin ? 'Super admin' : 'Admin'}, with an ${status === AccountStatus.Active ? 'active' : 'inactive'} account?`); };
  return <Workspace title="Admin management"><Heading title="The people behind the platform." description="Create administrator accounts and manage roles and account access." eyebrow="ADMINISTRATOR MANAGEMENT" action={<button className="primary" onClick={() => open(null)}>+ Add administrator</button>} /><LoadState loading={context.loading} error={context.error} retry={context.refreshAdmins} />{editing === undefined && <ErrorMessage error={error} retry={context.refreshAdmins} />}
  {!context.loading && !context.error && <><div className="toolbar"><div className="tabs">{[['all', 'All accounts'], ['0', 'Active'], ['1', 'Inactive']].map(([value, label]) => <button key={value} className={`tab ${filter === value ? 'active' : ''}`} onClick={() => setFilter(value)} aria-pressed={filter === value}>{label}</button>)}</div><input className="search" aria-label="Search administrators" type="search" placeholder="Search name or email…" value={search} onChange={e => setSearch(e.target.value)} /></div><div className="tablewrap"><div className="tabletitle"><h2>Administrator accounts</h2><small>{context.admins.length} accounts · {context.admins.filter(a => a.status === AccountStatus.Active).length} active</small></div><table><thead><tr><th>Name & email</th><th>Role</th><th>Account status</th><th>Actions</th></tr></thead><tbody>{visible.map(a => <tr key={a.adminId}><td><strong>{a.userName}</strong><small>{a.email}</small></td><td data-label="Role">{a.adminRole === AdminRole.SuperAdmin ? 'Super admin' : 'Admin'}</td><td data-label="Status"><Badge tone={a.status === AccountStatus.Active ? 'green' : 'gray'}>{a.status === AccountStatus.Active ? 'Active' : a.status === AccountStatus.Pending ? 'Pending' : a.status === AccountStatus.Deleted ? 'Deleted' : 'Inactive'}</Badge></td><td data-label="Actions"><div className="pills"><button className="secondary" disabled={busy} onClick={() => open(a)}>Edit</button><button className="secondary" disabled={busy} onClick={() => void perform(() => context.updateAdmin(a.adminId, { userName: a.userName, email: a.email, adminRole: a.adminRole, status: a.status === AccountStatus.Active ? AccountStatus.InActive : AccountStatus.Active }), `${a.status === AccountStatus.Active ? 'Deactivate' : 'Restore'} ${a.userName}?`)}>{a.status === AccountStatus.Active ? 'Deactivate' : 'Restore'}</button><button className="danger" disabled={busy} onClick={() => void perform(() => context.deleteAdmin(a.adminId), `Delete ${a.userName}'s administrator account?`)}>Delete</button></div></td></tr>)}</tbody></table></div>{!visible.length && <Empty>No administrators match this view.</Empty>}<div className="fieldnote">Super admins manage other administrators; regular admins review companies, customers and simulated payments.</div></>}
  {editing !== undefined && <Modal title={editing ? 'Edit administrator' : 'Add an administrator'} onClose={() => { if (!busy) { setEditing(undefined); setError(''); setPassword(''); } }}><ErrorMessage error={error} /><form onSubmit={submit}><fieldset disabled={busy} style={{ border: 0, padding: 0, margin: 0 }}><div className="formgrid"><Field label="Full name" full><input name="userName" value={name} onChange={e => setName(e.target.value)} required maxLength={100} /></Field><Field label="Email address" full><input name="email" value={email} onChange={e => setEmail(e.target.value)} type="email" required /></Field><Field label="Role"><select name="adminRole" value={role} onChange={e => setRole(Number(e.target.value) as AdminRole)}><option value={AdminRole.Admin}>Admin</option><option value={AdminRole.SuperAdmin}>Super admin</option></select></Field><Field label="Account status"><select name="status" value={status} onChange={e => setStatus(Number(e.target.value) as AccountStatus)}><option value={AccountStatus.Active}>Active</option><option value={AccountStatus.InActive}>Inactive</option></select></Field><Field label="Password" full><input name="password" value={password} onChange={e => setPassword(e.target.value)} type="password" minLength={12} required={!editing} autoComplete="new-password" /></Field></div><p className="hint">{editing ? 'Leave blank to keep the current password. A new password needs at least 12 characters.' : 'At least 12 characters. Required for a new account.'}</p><div className="buttonrow"><button type="button" className="secondary" onClick={() => { setEditing(undefined); setPassword(''); setError(''); }}>Cancel</button><button className="primary">{busy ? 'Saving…' : 'Review & save →'}</button></div></fieldset></form></Modal>}
  </Workspace>;
}
