import { useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import Workspace, { Heading, Notice, Panel, Review, Badge, Empty, LoadState, ErrorMessage } from '../../components/Workspace/Workspace';
import ProjectRow from '../../components/Workspace/ProjectRow';
import { useCompanyJobs } from '../../context/CompanyJobsContext';
import { getJobStatusLabel } from '../../utils/jobLabels';
import { formatCurrency } from '../../utils/quoteMath';
export default function CompanyApplications() {
  const { jobs, loading, error, refreshJobs, transitionJob } = useCompanyJobs();
  const [filter, setFilter] = useState('requested'), [search, setSearch] = useState(''), [selected, setSelected] = useState(''), [busy, setBusy] = useState(false), [actionError, setActionError] = useState('');
  const saving = useRef(false);
  const visible = jobs.filter(j => (filter === 'all' || j.status === filter) && j.description.toLowerCase().includes(search.trim().toLowerCase()));
  const job = jobs.find(j => j.id === selected) ?? visible[0];
  const decide = async (action: 'accept' | 'reject') => { if (!job || saving.current || !window.confirm(`${action === 'accept' ? 'Accept' : 'Reject'} this project request?`)) return; saving.current = true; setBusy(true); setActionError(''); try { await transitionJob(job.id, action); } catch (reason) { setActionError(reason instanceof Error ? reason.message : 'Could not save the decision.'); } finally { saving.current = false; setBusy(false); } };
  return <Workspace title="Company requests"><Heading title="Make the next move." description="Review new project requests and decide which work your company can take on." eyebrow="INCOMING REQUESTS" action={<Link className="secondary" to="/company/jobs">View all projects</Link>} /><Notice title="Acceptance comes first">Workers can be assigned after you accept a job. The customer must accept your quote before work starts.</Notice><LoadState loading={loading} error={error} retry={refreshJobs} /><ErrorMessage error={actionError} retry={refreshJobs} />
    {!loading && !error && <><div className="toolbar"><div className="tabs">{[['requested', 'Awaiting decision'], ['accepted', 'Accepted'], ['rejected', 'Rejected'], ['all', 'All requests']].map(([value, label]) => <button key={value} className={`tab ${filter === value ? 'active' : ''}`} onClick={() => { setFilter(value); setSelected(''); }} aria-pressed={filter === value}>{label}</button>)}</div><input className="search" type="search" value={search} onChange={e => setSearch(e.target.value)} aria-label="Search requests" placeholder="Search request…" /></div><div className="split"><div className="rowlist">{visible.map(j => <ProjectRow key={j.id} job={j} onReview={() => { setSelected(j.id); setActionError(''); }} />)}{!visible.length && <Empty>No requests match this view.</Empty>}</div>{job && <Panel title={job.title}><span className="eyebrow">REQUEST · {job.id.slice(-6).toUpperCase()}</span><Badge>{getJobStatusLabel(job.status)}</Badge><p style={{ marginTop: 18 }}>{job.description}</p><div className="divider" /><Review items={[["Dates", job.dateRange], ["Working days", job.daysWorking ?? 'Unavailable'], ["Location", job.address ? `${job.address.streetAddress}, ${job.address.city}` : 'Unavailable'], ["Quote", job.quoteSentAt ? formatCurrency(job.quoteAmount) : 'Not sent']]} /><div className="fieldnote">Acceptance allows you to quote and assign workers. The customer decides whether to accept the quote.</div>{job.status === 'requested' ? <div className="buttonrow" style={{ marginTop: 20 }}><button className="primary" disabled={busy} onClick={() => void decide('accept')}>Accept request</button><button className="danger" disabled={busy} onClick={() => void decide('reject')}>Reject</button></div> : <Link className="secondary" style={{ marginTop: 20 }} to={'/company/jobs/' + job.id}>Open project →</Link>}</Panel>}</div></>}
  </Workspace>;
}
