import { useRef, useState, type FormEvent } from 'react';
import { useSearchParams } from 'react-router-dom';
import Workspace, { Heading, Stats, Empty, Badge, LoadState, ErrorMessage } from '../../components/Workspace/Workspace';
import { Field } from '../../components/Workspace/Forms';
import Modal from '../../components/Workspace/Modal';
import { useWorkforce } from '../../context/WorkforceContext';
import { useCompanyJobs } from '../../context/CompanyJobsContext';
import { WorkerStatus, type Worker } from '../../types/worker';
import { getWorkerStatusLabel } from '../../utils/workerLables';
import { getJobStatusLabel } from '../../utils/jobLabels';
import { apiRequest } from '../../utils/api';
import { dataChanged } from '../../hooks/useApiResource';
type Mode = { kind: 'add' | 'edit' | 'assign'; worker?: Worker } | null;
export default function CompanyWorkforce() {
  const workforce = useWorkforce(), company = useCompanyJobs(), [query] = useSearchParams();
  const [search, setSearch] = useState(''), [filter, setFilter] = useState('all'), [mode, setMode] = useState<Mode>(null);
  const [first, setFirst] = useState(''), [last, setLast] = useState(''), [status, setStatus] = useState<WorkerStatus>(WorkerStatus.Active), [assignment, setAssignment] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const saving = useRef(false);
  const eligible = company.jobs.filter(j => !!j.acceptedAt && ['accepted', 'in-progress'].includes(j.status));
  const workers = workforce.workers;
  const visible = workers.filter(w => (filter === 'all' || String(w.workerStatus) === filter) && `${w.workerFirstName} ${w.workerLastName}`.toLowerCase().includes(search.trim().toLowerCase()));
  const open = (kind: NonNullable<Mode>['kind'], worker?: Worker) => { setError(''); setMode({ kind, worker }); setFirst(worker?.workerFirstName ?? ''); setLast(worker?.workerLastName ?? ''); setStatus(worker?.workerStatus ?? WorkerStatus.Active); setAssignment(worker?.jobId ?? (eligible.some(j => j.id === query.get('jobId')) ? query.get('jobId')! : '')); };
  const perform = async (action: () => Promise<unknown>, close = true) => { if (saving.current) return; saving.current = true; setBusy(true); setError(''); try { await action(); if (close) setMode(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save this worker.'); } finally { saving.current = false; setBusy(false); } };
  const submit = (event: FormEvent) => { event.preventDefault(); if (!mode) return;
    if (mode.kind !== 'assign' && (!first.trim() || !last.trim())) { setError('First and last names are required.'); return; }
    if (mode.kind === 'add') void perform(() => workforce.addWorker({ workerFirstName: first, workerLastName: last, workerStatus: status, jobId: null }));
    else if (mode.kind === 'assign') { if (assignment && !eligible.some(j => j.id === assignment)) { setError('Choose an accepted or in-progress job, or leave unassigned.'); return; } void perform(() => workforce.assignWorker(mode.worker!.workerId, assignment || null)); }
    else void perform(async () => { await apiRequest(`/api/Workers/${mode.worker!.workerId}`, { method: 'PUT', body: JSON.stringify({ workerFirstName: first.trim(), workerLastName: last.trim(), workerStatus: status }) }); dataChanged(); });
  };
  return <Workspace title="Company workforce"><Heading title="Your team, ready to build." description="Add workers to your workforce first. Assign them when a job has been accepted." eyebrow="COMPANY WORKFORCE" action={<button className="primary" onClick={() => open('add')}>+ Add worker</button>} /><LoadState loading={workforce.loading} error={workforce.error} retry={workforce.refreshWorkers} />{!mode && <ErrorMessage error={error} retry={() => { workforce.refreshWorkers(); company.refreshJobs(); }} />}
  {!workforce.loading && !workforce.error && <><Stats items={[["Workers", workers.length, "People in your workforce"], ["Assigned", workers.filter(w => w.jobId != null).length, "On accepted or active projects"], ["Unassigned", workers.filter(w => w.jobId == null).length, "No current job assignment"]]} /><div className="toolbar"><div className="tabs">{[['all', 'All workers'], ['0', 'Active'], ['1', 'Inactive']].map(([value, label]) => <button className={`tab ${filter === value ? 'active' : ''}`} key={value} onClick={() => setFilter(value)} aria-pressed={filter === value}>{label}</button>)}</div><input className="search" aria-label="Search workers" type="search" placeholder="Search worker…" value={search} onChange={e => setSearch(e.target.value)} /></div><div className="tablewrap"><div className="tabletitle"><h2>Workforce</h2><small>Account status and assignment are separate</small></div><table><thead><tr><th>Worker</th><th>Status</th><th>Current job</th><th>Actions</th></tr></thead><tbody>{visible.map(w => <tr key={w.workerId}><td><div className="identity"><span className="avatar" aria-hidden="true">{w.workerFirstName[0]}{w.workerLastName[0]}</span><strong>{w.workerFirstName} {w.workerLastName}</strong></div></td><td data-label="Status"><Badge tone={w.workerStatus === WorkerStatus.Active ? 'green' : 'gray'}>{getWorkerStatusLabel(w.workerStatus)}</Badge></td><td data-label="Current job">{w.jobId ? company.jobs.find(j => j.id === w.jobId)?.title ?? (company.loading ? 'Loading project…' : 'Assigned project') : 'Not assigned'}</td><td data-label="Actions"><div className="pills"><button className="secondary" disabled={busy} onClick={() => open('assign', w)}>{w.jobId ? 'Change job' : 'Assign'}</button><button className="secondary" disabled={busy} onClick={() => open('edit', w)}>Edit</button><button className="danger" disabled={busy} onClick={() => { if (window.confirm(`Remove ${w.workerFirstName} ${w.workerLastName} from your workforce?`)) void perform(() => workforce.deleteWorker(w.workerId), false); }}>Remove</button></div></td></tr>)}</tbody></table></div>{!visible.length && <Empty>No workers match this view.</Empty>}<div className="fieldnote">Only accepted or in-progress jobs are available for assignment. Requested and closed jobs are excluded.</div></>}
  {mode && <Modal title={mode.kind === 'add' ? 'Add a worker' : mode.kind === 'edit' ? 'Edit worker' : 'Manage assignment'} onClose={() => { if (!busy) { setMode(null); setError(''); } }}><ErrorMessage error={error} retry={() => { company.refreshJobs(); workforce.refreshWorkers(); }} /><form onSubmit={submit}><fieldset disabled={busy} style={{ border: 0, margin: 0, padding: 0 }}>{mode.kind === 'assign' ? <><p className="subtext" style={{ marginBottom: 15 }}>{mode.worker?.workerFirstName} {mode.worker?.workerLastName}</p><LoadState loading={company.loading} error={company.error} retry={company.refreshJobs} /><Field label="Job assignment"><select name="jobId" value={assignment} onChange={e => setAssignment(e.target.value)} disabled={company.loading || !!company.error}><option value="">No job · leave unassigned</option>{eligible.map(j => <option key={j.id} value={j.id}>{j.title} · {getJobStatusLabel(j.status)}</option>)}</select></Field><div className="fieldnote">A job appears here only after your company accepts it.</div></> : <><div className="formgrid"><Field label="First name"><input name="workerFirstName" value={first} onChange={e => setFirst(e.target.value)} required maxLength={100} /></Field><Field label="Last name"><input name="workerLastName" value={last} onChange={e => setLast(e.target.value)} required maxLength={100} /></Field><Field label="Worker status" full><select name="workerStatus" value={status} onChange={e => setStatus(Number(e.target.value) as WorkerStatus)}>{Object.values(WorkerStatus).map(s => <option key={s} value={s}>{getWorkerStatusLabel(s)}</option>)}</select></Field></div><div className="fieldnote">{mode.kind === 'add' ? 'This worker joins without a job. Assign them separately when you are ready.' : 'Editing worker details does not change their job assignment.'}</div></>}
  <div className="buttonrow"><button type="button" className="secondary" onClick={() => { setMode(null); setError(''); }}>Cancel</button><button className="primary" disabled={mode.kind === 'assign' && (company.loading || !!company.error)}>{busy ? 'Saving…' : mode.kind === 'add' ? 'Add worker' : 'Save changes'}</button></div></fieldset></form></Modal>}
  </Workspace>;
}
